[package]
name = "rusty-bandwidth"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["rustls-tls"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
percent-encoding = "2.3"
clap = { version = "4", features = ["derive", "env"] }
image = "0.24"
webp = "0.2"
